/* eslint-disable jsx-a11y/alt-text */
import Head from 'next/head';
import Nav from '../components/Nav'
import Header from '../components/Header'
import About from '../components/About'
import Projects from '../components/Projects';
import Contact from '../components/Contact';
import Footer from '../components/Footer';

import { useState } from 'react';

export default function Home() {
  const [darkMode, setDarkMode] = useState(false);
  return (
    <div class={darkMode ? 'dark' : ''}>
      <Head>
        <title>Satoe Sakonjo Portofolio</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
        <link rel="preconnect" href="https://fonts.googleapis.com" />
        <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin />
        <link href="https://fonts.googleapis.com/css2?family=Lora:wght@400;500;600&family=Nunito:wght@200;300;400;500;600&display=swap" rel="stylesheet" />

      </Head>
      <main className='bg-[#eae7dc] dark:bg-navy'>
        <section className="min-h-screen px-10 md:px-20 lg:px-40">
          <Nav />
          <Header />
        </section>
        <section className="min-h-screen">
          <About />
        </section>
        <Projects />
        <Contact />
        <Footer />
        
      </main>
    </div>
  )
}
